### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elm-datepicker#10]
@Danwhy are you up for researching the most effective way of testing this?

**Comment by Danwhy** [comment]
:+1: Absolutely

**Comment by Danwhy** [comment]
As of https://github.com/dwyl/elm-datepicker/pull/19, we have unit tests for all exposed functions.
I'm going to look at setting up some integration tests with our examples and cypress next.

**Comment by jorgengranseth** [comment]
And this @nelsonic ?

**Comment by nelsonic** [comment]
Yeah, with the CY tests and Elm Tests, this issue is done. ✅ 
@jorgengranseth thanks for tidying up the issues. 👍
