### ISSUE TITLE
Create various examples to show multiple use cases

### ISSUE THREAD

**Issue by iteles** [dwyl/elm-datepicker#4]
`As a` **developer** considering using this elm package in my project,
`I want` to see multiple examples of how I can use this package
`So that` I can get some inspiration for how to use it and see if it meets my needs.

Linked to #3

**Comment by jorgengranseth** [comment]
This is addressed, or are there other examples that should be added to close this? @iteles @nelsonic

**Comment by nelsonic** [comment]
Examples are looking good. 👍 
Thanks again @Danwhy ❤️
