### ISSUE TITLE
Changes necessary for module implementation

### ISSUE THREAD

**Issue by Danwhy** [dwyl/elm-datepicker#6]
In order to implement the abstracted datepicker module back into the project it originally came from, We need to make a few changes:

- [x] The model is no longer accessible, so we'll need helper functions to access any relevant data in it.
- [x] The `showCalendar` function should accept the individual month again, as well as just the model, so that it can display any month/year.

**Comment by nelsonic** [comment]
Looking great @Danwhy 🎉
