### ISSUE TITLE
DatePicker commands

### ISSUE THREAD

**Issue by andrewMacmurray** [dwyl/elm-datepicker#7]
Awesome that you're open sourcing this! 👌 

I spotted one thing that might make your API a little easier to manage (but obvs ignore this if it doesn't apply to your use case)

In your `DatePicker.update` https://github.com/dwyl/elm-datepicker/blob/master/src/DatePicker.elm#L361-L448 it doesn't look like you're using any commands. You could simplify the type signature from:

```elm
update : Msg -> DatePicker -> (DatePicker, Cmd Msg)
```

to

```elm
update : Msg -> DatePicker -> DatePicker
```

And would mean your client code that uses the datePicker wouldn't need to funnel commands back up from `DatePicker.update`, so:

```elm
datePickerUpdate : DatePicker.Msg -> Model -> ( Model, Cmd Msg )
datePickerUpdate datePickerMsg model =
    let
        ( dateModel, dateCmd ) =
            DatePicker.update datePickerMsg model.calendar
    in
        { model | calendar = dateModel } ! [ Cmd.map DatePickerMsg dateCmd ]
```

Would become:

```elm
datePickerUpdate : DatePicker.Msg -> Model -> ( Model, Cmd Msg )
datePickerUpdate datePickerMsg model =
        { model | calendar = DatePicker.update datePickerMsg model.calendar } ! []
```

But if you're going to use commands in the datePicker ignore this.

**Comment by andrewMacmurray** [comment]
@Danwhy no worries! It's a relief from Java at the moment 😂🤓

**Comment by nelsonic** [comment]
It might be useful to try to think of a use case for `command` in DatePicker ...
I _can_ think of a couple of situations where we would want it to return/run a `cmd`;
e.g: _automatically_ trigger a lookup/filter when dates are selected. 

Our _current_ projects (CI/TC) do _not_ require the `Cmd Msg` 
but imagine that the Date Selector widget was a **_single_ input** (_without a "submit" `<button>`_)
such as in a https://doodle.com then having `cmd` be triggered once the date selection is made without needing to click/tap another button.

I'm happy to _remove_ the `cmd` until we have a real _need_ for it.
It's entirely possible that we _won't_ need it ... 🤔 

This is a good post on the subject:
https://medium.com/elm-shorts/how-to-turn-a-msg-into-a-cmd-msg-in-elm-5dd095175d84

**Comment by andrewMacmurray** [comment]
@nelsonic Ah yes I see what you mean, maybe you could have two versions of DatePicker.update, one with the cmds and one for the simpler case?

**Comment by nelsonic** [comment]
@andrewMacmurray "_cross that bridge_" ... 😉 

Java ... ☕️ 
You've unlocked a whole other level of XKCD! 😜 
https://xkcd.com/1084
![image](https://user-images.githubusercontent.com/194400/39320334-aab1d826-497b-11e8-8255-e8db9df8495d.png)
https://xkcd.com/974/
![image](https://user-images.githubusercontent.com/194400/39320451-0b309340-497c-11e8-9289-fccb34ec29cd.png)

**Comment by andrewMacmurray** [comment]
@nelsonic 😂😂😂

**Comment by jorgengranseth** [comment]
Close this @nelsonic ?

**Comment by nelsonic** [comment]
Done. 👍
