### ISSUE TITLE
Keeping Msg constructors private

### ISSUE THREAD

**Issue by andrewMacmurray** [dwyl/elm-datepicker#9]
The only other thing I spotted was that you're exposing all the constructors on your `DatePicker.Msg`:

```elm
module DatePicker
    exposing
        ( Msg(..)
        , .....
        )
```

This is generally not a great idea for libraries as it means client code using the datePicker has to import the `Msg` type and its constructors for updating the datePicker's model:

```elm
module MyPage exposing (..)

import DatePicker exposing (Msg(..))
import MyPageTypes exposing (Msg(..))
```

This may not seem like a problem on smaller projects but sometimes you can get annoying name clashes with constructors of other `Msg`s. Plus you often end up exposing functionality you don't want your client to call directly (particularly if you add more `Msg`s over time to your datePicker that handle internal details)

It might be a better idea to only expose the `Msg` type and not its constructors (also known as an [opaque type](https://medium.com/@ckoster22/advanced-types-in-elm-opaque-types-ec5ec3b84ed2))

```elm
module DatePicker
    exposing
        ( Msg
        , .....
        )
```

and either:

expose individual `Msg`s via a function / value

```elm
nextMonth : DatePicker.Msg
nextMonth =
    NextMonth
```

or you could even combine them with `DatePicker.update` and refine your client api

```elm
nextMonth : DatePicker -> DatePicker
nextMonth =
    update NextMonth
```

Benefits of this approach are:

- You can prefix those operations with `DatePicker`, eg: `DatePicker.nextMonth` which can make it clearer in your client code where datePicker is being used
- no naming clashes
- You can restrict access to functionality by only exposing the message types you want your client to use

Sorry that's a bit of a ramble! Let me know if that doesn't make sense.

**Comment by Danwhy** [comment]
Yeah that makes perfect sense.
I did actually think of this before, but forgot about it, so thanks for reminding me! I've implemented something similar for the model already, so I'll definitely go ahead with this.

**Comment by jorgengranseth** [comment]
This can be closed? @Danwhy @nelsonic

**Comment by nelsonic** [comment]
Yeah resolved. Closing. 👍 
Thanks again @andrewMacmurray & @Danwhy ❤️
